// <auto-generated />
using System;
using ApostasApp.Core.InfraStructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApostasApp.Core.InfraStructure.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20250709152945_FinalFixApostaRodadaFK")]
    partial class FinalFixApostaRodadaFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Apostadores.Apostador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Apostadores", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Apostas.ApostaRodada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApostadorCampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CustoPagoApostaRodada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataHoraSubmissao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhApostaCampeonato")
                        .HasColumnType("bit");

                    b.Property<bool>("EhApostaIsolada")
                        .HasColumnType("bit");

                    b.Property<bool>("Enviada")
                        .HasColumnType("bit");

                    b.Property<string>("IdentificadorAposta")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PontuacaoTotalRodada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RodadaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApostadorCampeonatoId");

                    b.HasIndex("RodadaId");

                    b.ToTable("ApostasRodada", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Apostas.Palpite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApostaRodadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PlacarApostaCasa")
                        .HasColumnType("int");

                    b.Property<int?>("PlacarApostaVisita")
                        .HasColumnType("int");

                    b.Property<decimal>("Pontos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApostaRodadaId");

                    b.HasIndex("JogoId");

                    b.ToTable("Palpites", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Campeonatos.ApostadorCampeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApostadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CustoAdesaoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Pontuacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Posicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("ApostadorId", "CampeonatoId")
                        .IsUnique();

                    b.ToTable("ApostadoresCampeonatos", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Campeonatos.Campeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CustoAdesao")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInic")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumRodadas")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Campeonatos", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Campeonatos.EquipeCampeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("EquipeId");

                    b.ToTable("EquipesCampeonatos", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Equipes.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Escudo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid>("UfId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UfId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Estadios.Estadio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("UfId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UfId");

                    b.ToTable("Estadios", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Financeiro.Saldo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApostadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApostadorId")
                        .IsUnique();

                    b.ToTable("Saldos", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Financeiro.TransacaoFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApostaRodadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("SaldoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApostaRodadaId");

                    b.HasIndex("SaldoId");

                    b.ToTable("TransacoesFinanceiras", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Jogos.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataJogo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EquipeCasaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipeVisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstadioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("HoraJogo")
                        .HasColumnType("time");

                    b.Property<int?>("PlacarCasa")
                        .HasColumnType("int");

                    b.Property<int?>("PlacarVisita")
                        .HasColumnType("int");

                    b.Property<Guid>("RodadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeCasaId");

                    b.HasIndex("EquipeVisitanteId");

                    b.HasIndex("EstadioId");

                    b.HasIndex("RodadaId");

                    b.ToTable("Jogos", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.RankingRodadas.RankingRodada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApostadorCampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<int>("Posicao")
                        .HasColumnType("int");

                    b.Property<Guid>("RodadaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApostadorCampeonatoId");

                    b.HasIndex("RodadaId");

                    b.ToTable("RankingRodadas");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Rodadas.Rodada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CustoApostaRodada")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInic")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumJogos")
                        .HasColumnType("int");

                    b.Property<int>("NumeroRodada")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Rodadas", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Ufs.Uf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Ufs", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Usuarios.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Apostadores.Apostador", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Usuarios.Usuario", "Usuario")
                        .WithOne("Apostador")
                        .HasForeignKey("ApostasApp.Core.Domain.Models.Apostadores.Apostador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Apostas.ApostaRodada", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Campeonatos.ApostadorCampeonato", "ApostadorCampeonato")
                        .WithMany("ApostasRodada")
                        .HasForeignKey("ApostadorCampeonatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApostasApp.Core.Domain.Models.Rodadas.Rodada", "Rodada")
                        .WithMany("ApostasRodada")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApostadorCampeonato");

                    b.Navigation("Rodada");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Apostas.Palpite", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Apostas.ApostaRodada", "ApostaRodada")
                        .WithMany("Palpites")
                        .HasForeignKey("ApostaRodadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApostasApp.Core.Domain.Models.Jogos.Jogo", "Jogo")
                        .WithMany("Palpites")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApostaRodada");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Campeonatos.ApostadorCampeonato", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Apostadores.Apostador", "Apostador")
                        .WithMany("ApostadoresCampeonatos")
                        .HasForeignKey("ApostadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApostasApp.Core.Domain.Models.Campeonatos.Campeonato", "Campeonato")
                        .WithMany("ApostadoresCampeonatos")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apostador");

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Campeonatos.EquipeCampeonato", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Campeonatos.Campeonato", "Campeonato")
                        .WithMany("EquipesCampeonatos")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApostasApp.Core.Domain.Models.Equipes.Equipe", "Equipe")
                        .WithMany("EquipesCampeonatos")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Equipes.Equipe", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Ufs.Uf", "Uf")
                        .WithMany("Equipes")
                        .HasForeignKey("UfId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Estadios.Estadio", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Ufs.Uf", "Uf")
                        .WithMany("Estadios")
                        .HasForeignKey("UfId");

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Financeiro.Saldo", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Apostadores.Apostador", "Apostador")
                        .WithOne("Saldo")
                        .HasForeignKey("ApostasApp.Core.Domain.Models.Financeiro.Saldo", "ApostadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apostador");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Financeiro.TransacaoFinanceira", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Apostas.ApostaRodada", "ApostaRodada")
                        .WithMany()
                        .HasForeignKey("ApostaRodadaId");

                    b.HasOne("ApostasApp.Core.Domain.Models.Financeiro.Saldo", "Saldo")
                        .WithMany()
                        .HasForeignKey("SaldoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApostaRodada");

                    b.Navigation("Saldo");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Jogos.Jogo", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Campeonatos.EquipeCampeonato", "EquipeCasa")
                        .WithMany("JogosCasa")
                        .HasForeignKey("EquipeCasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApostasApp.Core.Domain.Models.Campeonatos.EquipeCampeonato", "EquipeVisitante")
                        .WithMany("JogosVisitante")
                        .HasForeignKey("EquipeVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApostasApp.Core.Domain.Models.Estadios.Estadio", "Estadio")
                        .WithMany()
                        .HasForeignKey("EstadioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApostasApp.Core.Domain.Models.Rodadas.Rodada", "Rodada")
                        .WithMany("JogosRodada")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipeCasa");

                    b.Navigation("EquipeVisitante");

                    b.Navigation("Estadio");

                    b.Navigation("Rodada");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.RankingRodadas.RankingRodada", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Campeonatos.ApostadorCampeonato", "ApostadorCampeonato")
                        .WithMany("RankingRodadas")
                        .HasForeignKey("ApostadorCampeonatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApostasApp.Core.Domain.Models.Rodadas.Rodada", "Rodada")
                        .WithMany("RankingRodadas")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApostadorCampeonato");

                    b.Navigation("Rodada");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Rodadas.Rodada", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Campeonatos.Campeonato", "Campeonato")
                        .WithMany("Rodadas")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApostasApp.Core.Domain.Models.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApostasApp.Core.Domain.Models.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Apostadores.Apostador", b =>
                {
                    b.Navigation("ApostadoresCampeonatos");

                    b.Navigation("Saldo")
                        .IsRequired();
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Apostas.ApostaRodada", b =>
                {
                    b.Navigation("Palpites");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Campeonatos.ApostadorCampeonato", b =>
                {
                    b.Navigation("ApostasRodada");

                    b.Navigation("RankingRodadas");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Campeonatos.Campeonato", b =>
                {
                    b.Navigation("ApostadoresCampeonatos");

                    b.Navigation("EquipesCampeonatos");

                    b.Navigation("Rodadas");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Campeonatos.EquipeCampeonato", b =>
                {
                    b.Navigation("JogosCasa");

                    b.Navigation("JogosVisitante");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Equipes.Equipe", b =>
                {
                    b.Navigation("EquipesCampeonatos");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Jogos.Jogo", b =>
                {
                    b.Navigation("Palpites");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Rodadas.Rodada", b =>
                {
                    b.Navigation("ApostasRodada");

                    b.Navigation("JogosRodada");

                    b.Navigation("RankingRodadas");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Ufs.Uf", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("Estadios");
                });

            modelBuilder.Entity("ApostasApp.Core.Domain.Models.Usuarios.Usuario", b =>
                {
                    b.Navigation("Apostador")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
