name: Trigger auto deployment for aca-bolao-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/aca-bolao-backend-AutoDeployTrigger-2bf79490-b2db-4316-af44-fd76f5122c80.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACABOLAOBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACABOLAOBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACABOLAOBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrbolaoestudosdesen.azurecr.io
          registryUsername: ${{ secrets.ACABOLAOBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACABOLAOBACKEND_REGISTRY_PASSWORD }}
          containerAppName: aca-bolao-backend
          resourceGroup: rg-estudos-desen
          imageToBuild: acrbolaoestudosdesen.azurecr.io/aca-bolao-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


