name: Deploy to env-bolao-prod (ACA Backend)

on:
  push:
    branches:  
      [ master ]    
    paths:
      # Paths para acionar o deploy apenas quando o código C# for alterado
      - 'src/ApostasApp.Core.Web/**' 
      - 'src/ApostasApp.Core.Application/**'
      - 'src/ApostasApp.Core.Domain/**'
      - 'src/ApostasApp.Core.Infrastructure/**'
      - 'Dockerfile'
      - '.github/workflows/aca-bolao-api-v1-AutoDeployTrigger-fdc66fde-00ce-4928-b72c-c42dc9a02fc9.yml'

  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      # **********************************************
      # 1. LOGIN NO AZURE (USANDO CREDENTIALS JSON)
      # **********************************************
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.ACABOLAOAPIV1_AZURE_CREDENTIALS }}

      # **********************************************
      # 2. LOGIN NO ACR
      # **********************************************
      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: acabolaoitems.azurecr.io
          username: ${{ secrets.ACABOLAOAPIV1_REGISTRY_USERNAME }}
          password: ${{ secrets.ACABOLAOAPIV1_REGISTRY_PASSWORD }}

      # **********************************************
      # 3. BUILD E PUSH MANUAL (Contornando Action Quebrada)
      # **********************************************
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="acabolaoitems.azurecr.io/aca-bolao-api-v1:${{ github.sha }}"
          
          # COMANDO BUILD DOCKER (Com o argumento de ignorar warnings)
          docker build . \
            --file Dockerfile \
            --tag $IMAGE_NAME \
            --build-arg TreatWarningsAsErrors=false 
            
          # COMANDO PUSH
          docker push $IMAGE_NAME

      # **********************************************
      # 4. DEPLOY MANUAL (Usando AZ CLI direto)
      # **********************************************
      - name: Deploy to Azure Container Apps
        uses: azure/cli@v1
        with:
          inlineScript: |
            # Imagem a ser usada no update
            IMAGE_NAME="acabolaoitems.azurecr.io/aca-bolao-api-v1:${{ github.sha }}"
            
            # Comando de update da ACA com a nova imagem
            az containerapp update \
              --name env-bolao-prod \
              --resource-group rg-bolao-aca-prod \
              --image $IMAGE_NAME \
              --target-port 8080 # Porta do seu Dockerfile
